spring.application.name=chat-app
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/chatapp
spring.datasource.username=s00298
spring.datasource.password=suraimukun$25
spring.flyway.baselineOnMigrate=true